### ISSUE TITLE
Android sharing

### ISSUE THREAD

**Issue by Skarpovich** [doomsower/react-native-vkontakte-login#18]
Hi! I've detected bug with sharing for android platform. I use the module like:
```javascript
    async onClickVk(){
        try {
            await VKLogin.initialize(constants.sharing.APP_ID_VK)
            const shareConfig = {
              linkText: constants.sharing.LINK_TEXT,
              linkUrl: this.url,
              description: constants.sharing.DESCRIPTION,
            }
            await VKLogin.share(shareConfig)
        } catch (error) {
            console.log('error', error);
        }
    }
```

it shows dialog.

![image](https://cloud.githubusercontent.com/assets/1862330/22246174/85bbf1ea-e244-11e6-8279-60b42ba4ccc8.png)

and display in console: 

```
01-24 15:22:26.097 9254-9302/com.testapp D/VKAuthModule: Inititalizing ${VK_APP_ID}
01-24 15:22:26.099 9254-9302/com.testapp D/VKAuthModule: Open Share Dialog
01-24 15:22:26.133 9254-9284/com.testapp W/EGL_emulation: eglSurfaceAttrib not implemented
01-24 15:22:26.133 9254-9284/com.testapp W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe21f4c00, error=EGL_SUCCESS
```

But when I press 'SEND' button, my application crashes with message 'Unfortunately TestApp has stopped'. And in console I see:

```
01-24 15:22:52.655 9254-9254/com.testapp D/AndroidRuntime: Shutting down VM
01-24 15:22:52.656 9254-9254/com.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.testapp, PID: 9254
    java.lang.NullPointerException: Attempt to read from field 'java.lang.String com.vk.sdk.VKAccessToken.userId' on a null object reference
        at com.vk.sdk.dialogs.VKShareDialogDelegate.makePostWithAttachments(VKShareDialogDelegate.java:330)
        at com.vk.sdk.dialogs.VKShareDialogDelegate.access$700(VKShareDialogDelegate.java:75)
        at com.vk.sdk.dialogs.VKShareDialogDelegate$4.onClick(VKShareDialogDelegate.java:377)
        at android.view.View.performClick(View.java:4780)
        at android.view.View$PerformClick.run(View.java:19866)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5254)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

`constants.sharing.APP_ID_VK` is number value

```
"dependencies": {
    ...
    "react-native": "0.39.0",
    "react-native-vkontakte-login": "^0.1.11",
    ...
  }
```

This bug detected on android 5.1 and android 4.1. Maybe I do anything wrong?

**Comment by doomsower** [comment]
In your code, you forgot to login before sharing something.
The sequence is initialize -> login -> share.
Since version 0.1.12 it should no longer crash hard in such situation, and will throw JS error.

**Comment by Skarpovich** [comment]
Thanks!
