### ISSUE TITLE
Safari cannot open the page because the address is invalid

### ISSUE THREAD

**Issue by NarekChang** [doomsower/react-native-vkontakte-login#50]
Получаю такую ошибку от in-app Safari. Происходит на этапе, когда нужно вернуться из браузера обратно в приложение.

**Comment by doomsower** [comment]
Могу предположить что URL схема из Info.plist не соответствует id приложения. Такое может быть если id приложения сменился с момента установки этого модуля.

**Comment by NarekChang** [comment]
@doomsower с момента создания react-native приложения или установки module'я для вк?

**Comment by NarekChang** [comment]
Если пробовать сделать react-native link, то получаем такую ошибку, может что-то даст:

```
info Linking "react-native-vkontakte-login" iOS dependency
info iOS module "react-native-vkontakte-login" has been successfully linked
info Linking "react-native-vkontakte-login" Android dependency
info Android module "react-native-vkontakte-login" has been successfully linked
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'react-native/local-cli/link/ios/createGroupWithMessage'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/username/Documents/test/node_modules/react-native-vkontakte-login/scripts/ios/modifyProject.js:6:48)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
/Users/frontend/Documents/winmobile/node_modules/@react-native-community/cli/build/tools/getHooks.js:37
        throw new Error(`Error occurred during executing "${command}" command`);
        ^

Error: Error occurred during executing "node node_modules/react-native-vkontakte-login/scripts/postlink" command
    at ChildProcess.commandProcess.on.code (/Users/frontend/Documents/winmobile/node_modules/@react-native-community/cli/build/tools/getHooks.js:37:15)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)

```

**Comment by doomsower** [comment]
С момента установки модуля. При установки модуля не-вручную в Info.plist спрашивается id приложения создаются записи для URL scheme. Вручную это вот  [тут](https://github.com/doomsower/react-native-vkontakte-login/blob/master/docs/installation.md#ios) 4 пункт.
Надо убедиться, что эти схемы соответствуют реально используему id приложения.

По последней ошибке: это похоже react-native-cli вынесли в коммьюнити-модуль и postlink скрипт сломался. Мне надо найти время и починить его.

**Comment by NarekChang** [comment]
Да, сработало по [инструкции](https://github.com/doomsower/react-native-vkontakte-login/blob/master/docs/installation.md#ios). Спасибо!

**Comment by alpamys-qanybet** [comment]
@NarekChang, привет, у тебя версия ReactNative какая?

**Comment by andrey-shostik** [comment]
```javascript
componentDidMount() {
  VKLogin.initialize(5514471);
}
```
Даже

**Comment by NarekChang** [comment]
@alpamys-qanybet v0.59.1
